spring.application.name=synkro

# server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:mariadb://${DATABASE_HOST}/${DATABASE_NAME}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

application.security.jwt.secret-key=${SYNKRO_SECRET}
application.security.jwt.access-token-expiration=${SYNKRO_JWT_EXPIRATION}
application.security.refresh-token-expiration=${SYNKRO_REFRESH_TOKEN_EXPIRATION_DAYS}
